# Basic
title: Qi 
subtitle: A blog for Qi
welcome_message: <a href="https://ww.google.com" target="_blank">Welcome</a>
description: All of life is an act of letting go, but what hurts the most is not taking a moment to say goodbye.
#Every single day without dancing is one day we betrayed of life.
creator: <a href="http://www.google.com">@onevcat</a>

url: "http://liuqi.zone"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://www.google.com"'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Qi
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: 
    twitter: 
    gplus: 
    mail: 

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
